name = "Whiteplain"
license = "MIT"
licenselink = "https://github.com/taikii/whiteplain/blob/master/LICENSE"
description = "Simple and functional theme for Hugo"
homepage = "https://github.com/taikii/whiteplain"
tags = []
features = []
min_version = "0.30"

[author]
  name = "taikii"
  homepage = "https://taikii.net/"
